from startup import *
from burnrate import rdp
from motor_library import MotorConfig


def calculate_pressure_parameters(N, motor: MotorConfig, c_star=0):
    """
    Calculates chamber pressure and timing parameters using a MotorConfig object.
    Replaces the legacy positional array indexing with named attributes.
    """
    # 1. Extract properties from the MotorConfig object
    prop = motor.prop
    Dt = motor.Dt
    Rho_pct = motor.Rho_pct
    Ng = motor.Ng
    L0 = motor.L
    De = motor.De
    Di = motor.Di
    csi, esi, osi = motor.csi, motor.esi, motor.osi

    # 2. Setup Chamber Geometry
    # Lc is the case length (with a 20% margin for spacers/o-rings)
    Lc = (Ng * L0) * 1.2
    Vc = (Lc * (pi / 4) * De ** 2) / 1000 ** 3  # Convert mm3 to m3

    # 3. Thermochemical Properties
    dp = dict_prop.get(prop.lower(), 2)
    rat = Ru / properties_table[2][dp]
    nuc = motor.nuc
    to = nuc * properties_table[3][dp]
    ratto = rat * to
    k = properties_table[1][dp]
    rho_ideal = properties_table[0][dp]
    rho_g = 1000 * rho_ideal * Rho_pct  # Density in kg/m3

    # Calculate Characteristic Velocity (C*) if not provided
    if c_star == 0:
        c_star = np.sqrt(ratto / k * (((k + 1) / 2) ** ((k + 1) / (k - 1))))

    # 4. Nozzle Parameters
    At = (pi / 4) * (Dt ** 2)  # mm2
    A_star = At / 1e6  # m2
    par_AI = np.sqrt(k / ratto) * (2 / (k + 1)) ** ((k + 1) / (2 * (k - 1)))

    # 5. Simulation Initialization
    tw0 = (De - Di) / 2  # Total web thickness to burn
    s = np.linspace(0, tw0, N)
    incs = s[1] - s[0]

    # Pre-allocate arrays for speed
    t = np.zeros(N)
    rdot = np.zeros(N)
    Pc_Mpa = np.ones(N) * patm
    m_grain = np.zeros(N)
    m_sto = np.zeros(N)

    # Initial state
    Vg0 = ((pi / 4) * (De ** 2 - Di ** 2) * L0 * Ng) / 1000 ** 3
    m_grain[0] = rho_g * Vg0
    rdot[0] = rdp(prop, patm)

    # 6. Main Simulation Loop
    for i in range(1, N):
        # Update Geometry based on inhibition
        # Current web burned = s[i]
        curr_di = Di + csi * 2 * s[i]
        curr_de = De - osi * 2 * s[i]
        curr_l = (L0 * Ng) - esi * 2 * s[i]

        # Surface Area and Volume
        Ab_mm2 = ((pi / 4) * (curr_de ** 2 - curr_di ** 2) * 2 * Ng * esi) + \
                 (pi * curr_de * curr_l * osi) + \
                 (pi * curr_di * curr_l * csi)

        Vg_m3 = ((pi / 4) * (curr_de ** 2 - curr_di ** 2) * curr_l) / (1000 ** 3)
        V_free = Vc - Vg_m3
        m_grain[i] = rho_g * Vg_m3

        # Physics: Pressure and Burn Rate
        # Mass generated by propellant
        rdot[i] = rdp(prop, Pc_Mpa[i - 1])
        t[i] = t[i - 1] + (incs / rdot[i])

        mdot_gen = (m_grain[i - 1] - m_grain[i]) / (t[i] - t[i - 1])

        # Mass flow through nozzle (Choked flow assumption)
        mdot_noz = (Pc_Mpa[i - 1] * 1e6) * A_star * par_AI

        # Mass storage and resulting pressure
        m_stodot = mdot_gen - mdot_noz
        m_sto[i] = m_sto[i - 1] + m_stodot * (t[i] - t[i - 1])

        rho_prod = m_sto[i] / V_free
        Pc_Mpa[i] = (rho_prod * ratto) / 1e6

    # 7. Tail-off Calculation (Depressurization)
    # Simple exponential decay after grain is consumed
    t_inc = 0.001
    tbout = t[-1]
    pbout = Pc_Mpa[-1]

    while Pc_Mpa[-1] > patm:
        t_next = t[-1] + t_inc
        p_next = pbout * np.exp(-ratto * A_star * (t_next - tbout) / (Vc * c_star))
        t = np.append(t, t_next)
        Pc_Mpa = np.append(Pc_Mpa, p_next)
        if len(t) > N * 2: break  # Safety break

    r_avg = np.average(rdot)

    return t, Pc_Mpa, k, tbout, r_avg, m_grain[0]


if __name__ == '__main__':
    # Test with the new library structure
    from motor_library import load_motor

    test_motor = load_motor("motor_12")
    t, pc, k, tb, ravg, m0 = calculate_pressure_parameters(1000, test_motor)
    print(f"Simulation complete for {test_motor.name}. Peak Pressure: {max(pc):.2f} MPa")