# reporting.py
import os
import copy
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from fpdf import FPDF
from startup import *
from motor_library import MotorConfig, get_config_table_data
from thrust import calculate_thrust

matplotlib.use('Agg')
from matplotlib import rcParams

# --- THEME PALETTE (Dark Blue, White, Teal) ---
COLOR_PRIMARY = (18, 30, 50)  # Deep Midnight Blue
COLOR_WHITE = (255, 255, 255)  # Crisp White
COLOR_TEAL = (0, 160, 170)  # Electric Teal
COLOR_NEUTRAL = (240, 245, 248)  # Light Blue-Grey
COLOR_TEXT = (50, 60, 70)  # Dark Slate

LOGO_FILENAME = 'tau_logo.png'


class DashboardPDF(FPDF):
    def header(self):
        # --- 0. BACKGROUND WATERMARK ---
        if os.path.exists(LOGO_FILENAME):
            original_y = self.get_y()
            wm_width = 140
            wm_x = (210 - wm_width) / 2
            wm_y = (297 - wm_width) / 2
            self.image(LOGO_FILENAME, x=wm_x, y=wm_y, w=wm_width)
            self.set_y(original_y)

        # --- 1. DARK BLUE HEADER BAR ---
        self.set_fill_color(*COLOR_PRIMARY)
        self.rect(0, 0, 210, 20, 'F')  # Reduced height slightly (22->20)

        # --- 2. LOGO / BRAND TEXT ---
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(*COLOR_TEAL)
        self.set_xy(10, 5)
        self.cell(0, 5, 'TAU ROCKET TEAM', 0, 0, 'L')

        # --- 3. MAIN TITLE ---
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(*COLOR_WHITE)
        self.set_xy(10, 10)
        self.cell(0, 8, 'SRM SIMULATION REPORT', 0, 0, 'L')

        # --- 4. TOP RIGHT LOGO ---
        if os.path.exists(LOGO_FILENAME):
            self.image(LOGO_FILENAME, x=185, y=2, w=16)

        # --- 5. ACCENT STRIP ---
        self.set_fill_color(*COLOR_TEAL)
        self.rect(0, 20, 210, 1.5, 'F')

        # Reduced spacing after header
        self.ln(22)

    def footer(self):
        self.set_y(-12)
        self.set_font('Helvetica', '', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by SRM Simulator', 0, 0, 'R')

    def draw_section_title(self, title):
        """Clean header with Teal underline - COMPACT VERSION"""
        self.ln(2)  # Reduced top margin
        self.set_font('Helvetica', 'B', 12)  # Slightly smaller font
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(0, 6, title.upper(), 0, 1, 'L')

        # Teal Underline
        self.set_fill_color(*COLOR_TEAL)
        self.rect(self.get_x(), self.get_y(), 30, 0.8, 'F')
        self.ln(3)  # Reduced bottom margin

    def draw_kpi_card(self, x, y, label, value, unit, is_primary=False):
        """Modern 'Card' style for stats"""
        width, height = 42, 24  # Reduced height (26->24)

        # Card Background
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(220, 220, 220)
        self.set_line_width(0.2)
        self.rounded_rect(x, y, width, height, 2, 'FD')

        # Left Accent Bar
        bar_color = COLOR_TEAL if is_primary else COLOR_PRIMARY
        self.set_fill_color(*bar_color)
        self.rounded_rect(x, y, 3, height, 2, 'F')
        self.rect(x + 1.5, y, 1.5, height, 'F')

        # Content
        off_x = x + 5
        self.set_xy(off_x, y + 3)
        self.set_font('Helvetica', 'B', 7)
        self.set_text_color(120, 130, 140)
        self.cell(width - 5, 4, label.upper(), 0, 0, 'L')

        self.set_xy(off_x, y + 9)
        self.set_font('Helvetica', 'B', 13)  # Slightly smaller value
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(width - 5, 7, value, 0, 0, 'L')

        self.set_xy(off_x, y + 16)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*COLOR_TEAL)
        self.cell(width - 5, 5, unit, 0, 0, 'L')

    def rounded_rect(self, x, y, w, h, r, style=''):
        """Helper to draw rounded rectangles"""
        k = 0.5522847498
        op = style.upper()
        if op == 'F':
            op_str = 'f'
        elif op == 'FD' or op == 'DF':
            op_str = 'B'
        else:
            op_str = 'S'
        self._out(f'{x + r:.2f} {y:.2f} m')
        self._out(f'{x + w - r:.2f} {y:.2f} l')
        self._out(f'{x + w - r + r * k:.2f} {y:.2f} {x + w:.2f} {y + r - r * k:.2f} {x + w:.2f} {y + r:.2f} c')
        self._out(f'{x + w:.2f} {y + h - r:.2f} l')
        self._out(
            f'{x + w:.2f} {y + h - r + r * k:.2f} {x + w - r + r * k:.2f} {y + h:.2f} {x + w - r:.2f} {y + h:.2f} c')
        self._out(f'{x + r:.2f} {y + h:.2f} l')
        self._out(f'{x + r - r * k:.2f} {y + h:.2f} {x:.2f} {y + h - r + r * k:.2f} {x:.2f} {y + h - r:.2f} c')
        self._out(f'{x:.2f} {y + r:.2f} l')
        self._out(f'{x:.2f} {y + r - r * k:.2f} {x + r - r * k:.2f} {y:.2f} {x + r:.2f} {y:.2f} c')
        self._out(op_str)

    def draw_clean_table(self, headers, data, col_widths, start_x=15):
        """Minimalist Table - Compact Rows"""
        self.set_x(start_x)
        row_height = 6  # Reduced from 7

        # Header
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(*COLOR_WHITE)
        self.set_fill_color(*COLOR_PRIMARY)
        self.set_draw_color(*COLOR_PRIMARY)

        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, 0, 0, 'C', fill=True)
        self.ln()

        # Data
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*COLOR_TEXT)
        self.set_draw_color(230, 230, 230)

        for idx, row in enumerate(data):
            self.set_x(start_x)
            if idx % 2 == 0:
                self.set_fill_color(255, 255, 255)
            else:
                self.set_fill_color(*COLOR_NEUTRAL)

            for i, d in enumerate(row):
                if i == 0:
                    self.set_font('Helvetica', 'B', 9)
                    self.set_text_color(*COLOR_PRIMARY)
                else:
                    self.set_font('Helvetica', '', 9)
                    self.set_text_color(*COLOR_TEXT)
                self.cell(col_widths[i], row_height, str(d), 'B', 0, 'C', fill=True)
            self.ln()


# --- HELPER: Class Calculator ---
def get_impulse_class(It):
    limits = [
        (2.5, 'A'), (5, 'B'), (10, 'C'), (20, 'D'), (40, 'E'), (80, 'F'),
        (160, 'G'), (320, 'H'), (640, 'I'), (1280, 'J'), (2560, 'K'),
        (5120, 'L'), (10240, 'M'), (20480, 'N'), (40960, 'O')
    ]
    return next((char for limit, char in limits if It <= limit), "P+")


# --- PLOTTING STYLE ---
def set_plot_style():
    plt.style.use('default')
    rcParams.update({
        'font.family': 'sans-serif',
        'font.sans-serif': ['Arial', 'Helvetica', 'DejaVu Sans'],
        'font.size': 8,  # Slightly smaller font
        'axes.facecolor': 'white',
        'axes.edgecolor': '#E0E0E0',
        'axes.linewidth': 0.8,
        'axes.grid': True,
        'grid.color': '#00a0aa',
        'grid.alpha': 0.1,
        'grid.linestyle': '-',
        'xtick.color': '#555555',
        'ytick.color': '#555555',
        'text.color': '#333333',
        'axes.labelcolor': '#121e32',
        'figure.facecolor': 'white',
        'savefig.dpi': 300,
        'savefig.bbox': 'tight'
    })


# ==========================================
# REPORT 1: INDIVIDUAL MOTOR (COMPACT)
# ==========================================
def create_pdf_report(motor: MotorConfig, t, Pc_MPa, F, It, filename="report.pdf"):
    set_plot_style()
    pdf = DashboardPDF()
    pdf.add_page()
    # Note: Header is auto-called, but we reduced its bottom spacing

    # 1. TITLE
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 5, f"Performance Analysis for Configuration: {motor.name}", 0, 1, 'L')

    # 2. KPI DASHBOARD
    peak_p = np.max(Pc_MPa)
    max_f = np.max(F)
    cls = get_impulse_class(It)

    start_y = pdf.get_y() + 2
    pdf.draw_kpi_card(15, start_y, "Total Impulse", f"{It:.1f}", f"Ns (Class {cls})", is_primary=True)
    pdf.draw_kpi_card(62, start_y, "Peak Pressure", f"{peak_p:.2f}", "MPa")
    pdf.draw_kpi_card(109, start_y, "Peak Thrust", f"{max_f:.0f}", "Newtons")
    pdf.draw_kpi_card(156, start_y, "Burn Time", f"{t[-1]:.2f}", "Seconds")

    pdf.set_y(start_y + 28)  # Reduced spacing (32->28)

    # 3. CONFIGURATION TABLE
    pdf.draw_section_title("Technical Specifications")
    config_headers = ["Parameter", "Value", "Unit"]
    config_data = get_config_table_data(motor)
    pdf.draw_clean_table(config_headers, config_data, [80, 50, 30], start_x=25)

    # 4. PLOTS (SIDE BY SIDE)
    pdf.draw_section_title("Thrust & Pressure Telemetry")
    temp_img = "temp_dashboard_plot.png"

    # Changed: 1 row, 2 columns. Aspect ratio 10:3.5 is wide and short.
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3.5))

    # Thrust (Teal) - Left
    ax1.plot(t, F, color='#00a0aa', linewidth=1.5, label='Thrust')
    ax1.fill_between(t, F, alpha=0.1, color='#00a0aa')
    ax1.set_xlabel('Time (s)')
    ax1.set_ylabel('Thrust (N)')
    ax1.set_title("Thrust Curve", fontsize=9, fontweight='bold', color='#00a0aa')
    ax1.grid(True, alpha=0.2)

    # Pressure (Dark Blue) - Right
    ax2.plot(t, Pc_MPa, color='#121e32', linewidth=1.5, label='Pressure')
    ax2.fill_between(t, Pc_MPa, alpha=0.05, color='#121e32')
    ax2.set_xlabel('Time (s)')
    ax2.set_ylabel('Pressure (MPa)')
    ax2.set_title("Chamber Pressure", fontsize=9, fontweight='bold', color='#121e32')
    ax2.grid(True, alpha=0.2)

    plt.tight_layout()
    plt.savefig(temp_img, dpi=300)
    plt.close(fig)

    # Image height is now controlled by aspect ratio.
    # Width 185mm. Ratio 10:3.5 -> Height approx 65mm.
    pdf.image(temp_img, x=12, w=185)
    if os.path.exists(temp_img): os.remove(temp_img)

    # 5. FOOTER SUMMARY
    pdf.ln(2)  # Minimal spacing
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 5, f"Summary: Class {cls} motor delivering {It:.0f} Ns with a peak thrust of {max_f:.0f} N.", 0, 1, 'C')

    # Ensure directory exists
    output_dir = os.path.dirname(filename)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    pdf.output(filename)
    print(f"✅ Design Report generated (Single Page): {filename}")


# ==========================================
# REPORT 2: SENSITIVITY (UNCHANGED)
# ==========================================
def create_sensitivity_report(base_motor, param_name, values_to_test, filename="sensitivity.pdf"):
    # (Kept exactly as it was, just ensuring imports work)
    set_plot_style()
    pdf = DashboardPDF()
    pdf.add_page()

    pdf.ln(2)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(*COLOR_PRIMARY)
    pdf.cell(0, 10, f"Sensitivity Analysis: Varying '{param_name}'", 0, 1, 'L')

    pdf.draw_section_title("Base Configuration")
    config_headers = ["Parameter", "Value", "Unit"]
    config_data = get_config_table_data(base_motor)
    pdf.draw_clean_table(config_headers, config_data, [80, 50, 30], start_x=25)
    pdf.ln(5)

    from thrust import calculate_thrust
    results_data = []

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
    import matplotlib.colors as mcolors
    cmap = mcolors.LinearSegmentedColormap.from_list("BlueTeal", ["#121e32", "#00a0aa"])
    colors = [cmap(i) for i in np.linspace(0, 1, len(values_to_test))]

    for i, val in enumerate(values_to_test):
        sim_motor = copy.deepcopy(base_motor)
        if hasattr(sim_motor, param_name):
            setattr(sim_motor, param_name, val)

        F, Pc, t, Cf, It = calculate_thrust(10000, sim_motor, 0.95, 6.278)
        peak_p = np.max(Pc)
        max_f = np.max(F)
        cls = get_impulse_class(It)
        val_str = f"{val:.3f}" if isinstance(val, (float, np.floating)) else str(val)
        results_data.append([val_str, f"{peak_p:.3f}", f"{max_f:.1f}", f"{It:.1f}", cls])

        ax1.plot(t, Pc, label=val_str, color=colors[i], linewidth=1.5, alpha=0.8)
        ax2.plot(t, F, color=colors[i], linewidth=1.5, alpha=0.8)

    for ax in [ax1, ax2]:
        ax.grid(True, color='#00a0aa', alpha=0.1)

    ax1.set_title("Chamber Pressure (MPa)", color='#121e32', fontweight='bold')
    ax1.set_xlabel("Time (s)")
    ax1.legend(title=param_name, fontsize=7, frameon=False)
    ax2.set_title("Thrust (N)", color='#00a0aa', fontweight='bold')
    ax2.set_xlabel("Time (s)")

    plt.tight_layout()
    temp_img = "temp_sens_plot.png"
    plt.savefig(temp_img, dpi=300)
    plt.close(fig)

    pdf.draw_section_title("Visual Comparison")
    pdf.image(temp_img, x=15, w=180)
    if os.path.exists(temp_img): os.remove(temp_img)

    pdf.ln(5)
    pdf.draw_section_title("Comparative Data")
    headers = [param_name, "Peak P (MPa)", "Max F (N)", "Impulse (Ns)", "Class"]
    pdf.draw_clean_table(headers, results_data, [35, 35, 35, 35, 30], start_x=20)

    output_dir = os.path.dirname(filename)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)
    print(f"✅ Sensitivity Report generated: {filename}")