import os
import matplotlib

# Force headless mode to prevent GUI crashes
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import rcParams
from fpdf import FPDF
from motor_library import MotorConfig
import numpy as np
import copy

# --- THEME PALETTE (Dark Blue, White, Teal) ---
COLOR_PRIMARY = (18, 30, 50)  # Deep Midnight Blue
COLOR_WHITE = (255, 255, 255)  # Crisp White
COLOR_TEAL = (0, 160, 170)  # Electric Teal
COLOR_NEUTRAL = (240, 245, 248)  # Light Blue-Grey
COLOR_TEXT = (50, 60, 70)  # Dark Slate

LOGO_FILENAME = 'tau_logo.png'


class DashboardPDF(FPDF):
    def header(self):
        # --- 0. BACKGROUND WATERMARK ---
        if os.path.exists(LOGO_FILENAME):
            original_y = self.get_y()
            wm_width = 140
            wm_x = (210 - wm_width) / 2
            wm_y = (297 - wm_width) / 2
            self.image(LOGO_FILENAME, x=wm_x, y=wm_y, w=wm_width)
            self.set_y(original_y)

        # --- 1. DARK BLUE HEADER BAR ---
        self.set_fill_color(*COLOR_PRIMARY)
        self.rect(0, 0, 210, 22, 'F')

        # --- 2. LOGO / BRAND TEXT ---
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(*COLOR_TEAL)
        self.set_xy(10, 6)
        self.cell(0, 5, 'TAU ROCKET TEAM', 0, 0, 'L')

        # --- 3. MAIN TITLE ---
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(*COLOR_WHITE)
        self.set_xy(10, 11)
        self.cell(0, 8, 'SRM SIMULATION REPORT', 0, 0, 'L')

        # --- 4. TOP RIGHT LOGO ---
        if os.path.exists(LOGO_FILENAME):
            self.image(LOGO_FILENAME, x=185, y=2, w=18)

        # --- 5. ACCENT STRIP ---
        self.set_fill_color(*COLOR_TEAL)
        self.rect(0, 22, 210, 1.5, 'F')
        self.ln(25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', '', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by SRM Simulator', 0, 0, 'R')

    def draw_section_title(self, title):
        self.ln(5)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(0, 8, title.upper(), 0, 1, 'L')
        self.set_fill_color(*COLOR_TEAL)
        self.rect(self.get_x(), self.get_y(), 30, 1, 'F')
        self.ln(6)

    def draw_kpi_card(self, x, y, label, value, unit, is_primary=False):
        width, height = 42, 26
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(220, 220, 220)
        self.set_line_width(0.2)
        self.rounded_rect(x, y, width, height, 2, 'FD')

        bar_color = COLOR_TEAL if is_primary else COLOR_PRIMARY
        self.set_fill_color(*bar_color)
        self.rounded_rect(x, y, 3, height, 2, 'F')
        self.rect(x + 1.5, y, 1.5, height, 'F')

        off_x = x + 5
        self.set_xy(off_x, y + 4)
        self.set_font('Helvetica', 'B', 7)
        self.set_text_color(120, 130, 140)
        self.cell(width - 5, 4, label.upper(), 0, 0, 'L')

        self.set_xy(off_x, y + 10)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(width - 5, 7, value, 0, 0, 'L')

        self.set_xy(off_x, y + 17)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*COLOR_TEAL)
        self.cell(width - 5, 5, unit, 0, 0, 'L')

    def rounded_rect(self, x, y, w, h, r, style=''):
        k = 0.5522847498
        op = style.upper()
        if op == 'F':
            op_str = 'f'
        elif op == 'FD' or op == 'DF':
            op_str = 'B'
        else:
            op_str = 'S'
        self._out(
            f'{x + r:.2f} {y:.2f} m {x + w - r:.2f} {y:.2f} l {x + w - r + r * k:.2f} {y:.2f} {x + w:.2f} {y + r - r * k:.2f} {x + w:.2f} {y + r:.2f} c {x + w:.2f} {y + h - r:.2f} l {x + w:.2f} {y + h - r + r * k:.2f} {x + w - r + r * k:.2f} {y + h:.2f} {x + w - r:.2f} {y + h:.2f} c {x + r:.2f} {y + h:.2f} l {x + r - r * k:.2f} {y + h:.2f} {x:.2f} {y + h - r + r * k:.2f} {x:.2f} {y + h - r:.2f} c {x:.2f} {y + r:.2f} l {x:.2f} {y + r - r * k:.2f} {x + r - r * k:.2f} {y:.2f} {x + r:.2f} {y:.2f} c {op_str}')

    def draw_clean_table(self, headers, data, col_widths, start_x=15):
        self.set_x(start_x)
        self.set_font('Helvetica', 'B', 9);
        self.set_text_color(255, 255, 255);
        self.set_fill_color(*COLOR_PRIMARY)
        for i, h in enumerate(headers): self.cell(col_widths[i], 8, h, 0, 0, 'C', fill=True)
        self.ln()
        for idx, row in enumerate(data):
            self.set_x(start_x)
            self.set_fill_color(255, 255, 255) if idx % 2 == 0 else self.set_fill_color(*COLOR_NEUTRAL)
            for i, d in enumerate(row):
                self.set_font('Helvetica', 'B' if i == 0 else '', 9)
                self.set_text_color(*(COLOR_PRIMARY if i == 0 else COLOR_TEXT))
                self.cell(col_widths[i], 7, str(d), 'B', 0, 'C', fill=True)
            self.ln()


def get_impulse_class(It):
    limits = [(2.5, 'A'), (5, 'B'), (10, 'C'), (20, 'D'), (40, 'E'), (80, 'F'), (160, 'G'), (320, 'H'), (640, 'I'),
              (1280, 'J'), (2560, 'K'), (5120, 'L'), (10240, 'M'), (20480, 'N'), (40960, 'O')]
    return next((char for limit, char in limits if It <= limit), "P+")


def set_plot_style():
    plt.style.use('default')
    rcParams.update({'font.size': 9, 'axes.facecolor': 'white', 'grid.color': '#00a0aa', 'grid.alpha': 0.1,
                     'axes.labelcolor': '#121e32', 'savefig.dpi': 300})


def get_config_table_data(motor):
    return [["Motor ID", motor.name, "-"], ["Propellant", motor.prop, "-"], ["Grain Length", f"{motor.L:.1f}", "mm"],
            ["Grain OD", f"{motor.De:.1f}", "mm"], ["Grain ID", f"{motor.Di:.1f}", "mm"],
            ["No. of Grains", str(motor.Ng), "-"], ["Throat Dia", f"{motor.Dt:.2f}", "mm"],
            ["Target Pressure", f"{motor.P_target:.1f}", "MPa"]]


def create_pdf_report(motor: MotorConfig, t, Pc_MPa, F, It, filename="report.pdf"):
    set_plot_style();
    pdf = DashboardPDF();
    pdf.add_page();
    peak_p = np.max(Pc_MPa);
    max_f = np.max(F);
    cls = get_impulse_class(It)
    start_y = pdf.get_y() + 2
    pdf.draw_kpi_card(15, start_y, "Total Impulse", f"{It:.1f}", f"Ns (Class {cls})", True)
    pdf.draw_kpi_card(62, start_y, "Peak Pressure", f"{peak_p:.2f}", "MPa")
    pdf.draw_kpi_card(109, start_y, "Peak Thrust", f"{max_f:.0f}", "Newtons")
    pdf.draw_kpi_card(156, start_y, "Burn Time", f"{t[-1]:.2f}", "Seconds")
    pdf.set_y(start_y + 32);
    pdf.draw_section_title("Technical Specifications")
    pdf.draw_clean_table(["Parameter", "Value", "Unit"], get_config_table_data(motor), [80, 50, 30], start_x=25)
    pdf.ln(8);
    pdf.draw_section_title("Thrust & Pressure Telemetry")
    temp_img = "temp_plot.png"
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 6), height_ratios=[1, 0.8])
    ax1.plot(t, F, color='#00a0aa', linewidth=2, label='Thrust');
    ax1.fill_between(t, F, alpha=0.1, color='#00a0aa');
    ax1.set_ylabel('Thrust (N)')
    ax2.plot(t, Pc_MPa, color='#121e32', linewidth=2, label='Pressure');
    ax2.set_xlabel('Time (s)');
    ax2.set_ylabel('Pressure (MPa)')
    plt.tight_layout();
    plt.savefig(temp_img);
    plt.close()
    pdf.image(temp_img, x=15, w=180)
    if os.path.exists(temp_img): os.remove(temp_img)
    pdf.output(filename)


def create_sensitivity_report(base_motor, param_name, values_to_test, filename="sensitivity.pdf"):
    set_plot_style();
    pdf = DashboardPDF();
    pdf.add_page();
    pdf.draw_section_title("Base Configuration")
    pdf.draw_clean_table(["Parameter", "Value", "Unit"], get_config_table_data(base_motor), [80, 50, 30], start_x=25)
    from thrust import calculate_thrust
    results_data = [];
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
    colors = plt.cm.viridis(np.linspace(0, 0.9, len(values_to_test)))
    for i, val in enumerate(values_to_test):
        sim_motor = copy.deepcopy(base_motor);
        setattr(sim_motor, param_name, val)
        F, Pc, t, Cf, It = calculate_thrust(10000, sim_motor, 0.95, 6.278)
        val_str = f"{val:.3f}" if isinstance(val, float) else str(val)
        results_data.append([val_str, f"{np.max(Pc):.3f}", f"{np.max(F):.1f}", f"{It:.1f}", get_impulse_class(It)])
        ax1.plot(t, Pc, label=val_str, color=colors[i], linewidth=1.5);
        ax2.plot(t, F, color=colors[i], linewidth=1.5)
    ax1.set_title("Pressure (MPa)");
    ax2.set_title("Thrust (N)");
    ax1.legend(title=param_name, fontsize=7)
    plt.tight_layout();
    temp_img = "temp_sens.png";
    plt.savefig(temp_img);
    plt.close()
    pdf.draw_section_title("Visual Comparison");
    pdf.image(temp_img, x=15, w=180)
    if os.path.exists(temp_img): os.remove(temp_img)
    pdf.ln(5);
    pdf.draw_section_title("Comparative Data")
    pdf.draw_clean_table([param_name, "Peak P", "Max F", "Impulse", "Class"], results_data, [35, 35, 35, 35, 30],
                         start_x=20)
    pdf.output(filename)