import os
import matplotlib.pyplot as plt
from fpdf import FPDF
from motor_library import MotorConfig
import numpy as np


class PDFReport(FPDF):
    def header(self):
        # Professional Header
        self.set_font('Arial', 'B', 15)
        self.cell(80)
        self.cell(30, 10, 'SRM Simulation Report', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by TauRocketTeam Simulator - Page ' + str(self.page_no()), 0, 0, 'C')


def create_pdf_report(motor: MotorConfig, t, Pc_MPa, F, It, filename="report.pdf"):
    """
    Generates a PDF summary of the simulation.
    Args:
        motor: The MotorConfig object used.
        t, Pc_MPa, F: Simulation arrays.
        It: Total Impulse.
        filename: Output filename.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # --- SECTION 1: Motor Configuration ---
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=f"Motor Configuration: {motor.name}", ln=1, align='L')

    pdf.set_font("Arial", size=11)
    # Create a simple table layout
    col_width = 80
    line_height = 7

    data_config = [
        ("Propellant", motor.prop),
        ("Grain Dimensions", f"OD: {motor.De}mm | ID: {motor.Di}mm | L: {motor.L}mm"),
        ("Number of Grains", str(motor.Ng)),
        ("Throat Diameter", f"{motor.Dt:.3f} mm"),
        ("Target Pressure", f"{motor.P_target} MPa"),
        ("Nozzle Efficiency", "0.95 (Assumed)")
    ]

    for label, value in data_config:
        pdf.cell(col_width, line_height, f"{label}:", border=0)
        pdf.cell(col_width, line_height, value, border=0)
        pdf.ln(line_height)

    pdf.ln(5)

    # --- SECTION 2: Performance Statistics ---
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Performance Statistics", ln=1, align='L')
    pdf.set_font("Arial", size=11)

    burn_time = t[-1]
    peak_pressure = np.max(Pc_MPa)
    max_thrust = np.max(F)
    avg_thrust = np.mean(F[F > 0])  # Average during burn only

    # Calculate Classification (approximate)
    # e.g., H-class is 160-320 Ns
    impulse_class = "Unknown"
    if 160 < It <= 320:
        impulse_class = "H"
    elif 320 < It <= 640:
        impulse_class = "I"
    elif 640 < It <= 1280:
        impulse_class = "J"

    data_stats = [
        ("Total Impulse", f"{It:.2f} Ns (Class {impulse_class})"),
        ("Peak Pressure", f"{peak_pressure:.3f} MPa"),
        ("Max Thrust", f"{max_thrust:.2f} N"),
        ("Average Thrust", f"{avg_thrust:.2f} N"),
        ("Burn Time", f"{burn_time:.3f} s")
    ]

    for label, value in data_stats:
        pdf.cell(col_width, line_height, f"{label}:", border=0)
        pdf.cell(col_width, line_height, value, border=0)
        pdf.ln(line_height)

    # --- SECTION 3: PLOTS ---
    # We generate the plot, save it as a temp image, insert it, then delete it.
    pdf.ln(5)

    # Generate Plot
    temp_img = "temp_plot_report.png"
    plt.figure(figsize=(10, 6))

    # Pressure Plot (Left Axis)
    fig, ax1 = plt.subplots(figsize=(8, 5))
    color = 'tab:red'
    ax1.set_xlabel('Time (s)')
    ax1.set_ylabel('Thrust (N)', color=color)
    ax1.plot(t, F, color=color, linewidth=2)
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True, alpha=0.3)

    # Thrust Plot (Right Axis)
    ax2 = ax1.twinx()
    color = 'tab:blue'
    ax2.set_ylabel('Pressure (MPa)', color=color)
    ax2.plot(t, Pc_MPa, color=color, linestyle='--', linewidth=1.5)
    ax2.tick_params(axis='y', labelcolor=color)

    plt.title(f"Performance Curves: {motor.name}")
    plt.tight_layout()
    plt.savefig(temp_img, dpi=150)
    plt.close()  # Close plot so it doesn't pop up

    # Embed in PDF
    # (x, y, w)
    pdf.image(temp_img, x=10, y=None, w=190)

    # Cleanup
    if os.path.exists(temp_img):
        os.remove(temp_img)

    # --- SAVE ---
    pdf.output(filename)
    print(f"✅ Report generated successfully: {filename}")